spring:
  profiles:
    active:
    -  dog
    -  EN
    -  prod
prakhar:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: Ymljdbc

---
spring:
  profiles: prod
prakhar:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdjdbc